version: "3"

services:
  hub:
    image: selenium/hub
    ports:
    - 4444:4444
  chrome:
    image: selenium/node-chrome
    depends_on:
    - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
  telegraf:
  image: telegraf
  restart: always
  environment:
    HOST_PROC: /rootfs/proc
    HOST_SYS: /rootfs/sys
    HOST_ETC: /rootfs/etc
  hostname: localhost
  volumes:
   - /home/ubuntu/telegraf.conf:/etc/telegraf/telegraf.conf:ro
   - /var/run/docker.sock:/var/run/docker.sock:ro
   - /sys:/rootfs/sys:ro
   - /proc:/rootfs/proc:ro
   - /etc:/rootfs/etc:ro
