version: "3"

services:
  hub:
    image: selenium/hub
    ports:
    - 4444:4444
  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
