version: "3"

services:
  hub:
    image: selenium/hub
    ports:
    - 4444:4444
  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
  prometheus:
    image: prom/prometheus
    volumes:
        - home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus_data:/prometheus
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'
  node-exporter:
        image: prom/node-exporter
        ports:
            - '9100:9100'        
volumes:
        prometheus_data: {}
